### ISSUE TITLE
In docker, luwu web-server error 

### ISSUE THREAD

**Issue by chanchann** [AaronJny/luwu#10]
ImportError: cannot import name 'LuwuPreTrainedImageClassifier' from 'luwu.core.models.classifier.preset' (/app/luwu/core/models/classifier/preset/__init__.py

**Comment by AaronJny** [comment]
有一个小bug，之前就解决了，但是最近比较忙，一直没有推到github上...抱歉抱歉
#11

**Comment by chanchann** [comment]
感谢大佬
