### ISSUE TITLE
关于Web UI

### ISSUE THREAD

**Issue by WangRongsheng** [AaronJny/luwu#14]
你好，请问web端用什么写，UI很好看，很感兴趣web端的开发，可以给些技术实现思路吗？

**Comment by AaronJny** [comment]
1. web端，前端框架使用的是vue，ui组件库使用的是 Element UI。我不是前端工程师，所以写的比较简陋，凑合着用的程度=。=
2. 是的，像你在邮件里面说的，是通过web端收集参数，创建任务，后台执行任务，再将结果反馈给前端。实际上会再稍微复杂一点点，实现一个简单的调度机制，用来完成运行、终止、重新运行、伪实时同步状态等操作，但基本思路就是前面说的那样。
